### ISSUE TITLE
[TES3MP-deploy] Installing in Ubuntu 14.04-x86

### ISSUE THREAD

**Issue by AJINJILIN** [GrimKriegor/Misc#1]
I tried to install in your instructions. That's what came out of it.
http://imgur.com/a/30jbp

**Comment by Koncord** [comment]
Try:
```
apt update
apt install git
```

**Comment by GrimKriegor** [comment]
Hey there AJINJILIN, thanks for testing the scripts.

The problems seems to be that git was not installed by the first set of instructions of the script, making everything that followed and relied on the files being downloaded by git fail.

Koncord suggested it might be because we were missing a command to refresh the package list, so those commands were added for every distro the script supports.

Could you please test again with the latest changes? Thank you for your time!

**Comment by AJINJILIN** [comment]
I had to manually install git pack. That solved the problem with the installation.
Now i have to get a binary, but with this I am having some problems.

> did the script detect you were running Ubuntu?
i think yes

**Comment by GrimKriegor** [comment]
Were you able to try with the new changes (re-downloading the scripts)?
The git package should be automatically installed alongside the other system dependencies, by the first instruction set of the script.
However it won't install any dependencies, including git, if it is not able to identify which GNU/Linux distro you are using.

The script should tell you *"You seem to be running either Debian, Ubuntu or Mint"*, if it told you *"Could not determine your GNU/Linux distro, press any key to continue without installing dependencies"* that means it does not know you are using Ubuntu.

I await your feedback, thanks for your time once again.

**Comment by AJINJILIN** [comment]
Well, I'll try to install again in the near future

**Comment by AJINJILIN** [comment]
http://i.imgur.com/2YPvyRm.png
